---
title: "RandomForests"
output: pdf_document
date: "2024-12-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Bagging

```{r}
length(names(df_train))
```

```{r}
library(randomForest)
```


# Bagging

```{r}

set.seed(1)
bag.rf = randomForest(log_pSat_Pa ~ ., data = df_train , mtry = 25, importance = TRUE)
```

# Random forest

Default mtry is P/3, 

```{r}

set.seed(1)
bag.rf = randomForest(log_pSat_Pa ~ ., data = df_train, mtry = 5, importance = TRUE)
```

```{r}
importance(bag.rf)
```


# Random forest

```{r}

importance(bag.rf)

```



```{r}
varImpPlot(bag.rf)
```

```{r}
yhat.bag = predict(bag.rf , newdata = test_data[,-1])
```

```{r}
ID = test_data$ID
TARGET = yhat.bag
df = data.frame(ID, TARGET)
write.csv(df[, c("ID", "TARGET")], "dummy_submission.csv", row.names = FALSE)
```


```{r}
fraction_c = train_data$NumOfC/train_data$NumOfAtoms
fraction_o = train_data$NumOfO/train_data$NumOfAtoms
fraction_n = train_data$NumOfN/train_data$NumOfAtoms
frcation_NumOfConfUsed = train_data$NumOfConfUsed /train_data$NumOfConf 

```

```{r}
Processes_df = train_data[,-c(1,4,5,6,7,9,10)]

```


```{r}
Processes_df["fraction_c"] = fraction_c
```

```{r}

Processes_df["fraction_o"] = fraction_o
Processes_df["fraction_n"] = fraction_n
Processes_df["frcation_NumOfConfUsed"] = frcation_NumOfConfUsed

```


```{r}
set.seed(1)
bag.rf = randomForest(log_pSat_Pa ~ ., data = Processes_df, mtry = 5, importance = TRUE)
```

```{r}
Processes_df_test = test_data[,-c(1,3,4,5,6,8,9)]

fraction_c = test_data$NumOfC/test_data$NumOfAtoms
fraction_o = test_data$NumOfO/test_data$NumOfAtoms
fraction_n = test_data$NumOfN/test_data$NumOfAtoms
frcation_NumOfConfUsed = test_data$NumOfConfUsed /test_data$NumOfConf 

Processes_df_test["fraction_c"] = fraction_c
Processes_df_test["fraction_o"] = fraction_o
Processes_df_test["fraction_n"] = fraction_n
Processes_df_test["frcation_NumOfConfUsed"] = frcation_NumOfConfUsed




```

```{r}
yhat.bag = predict(bag.rf , newdata = Processes_df_test)
```

```{r}
ID = test_data$ID
TARGET = yhat.bag
df = data.frame(ID, TARGET)
write.csv(df[, c("ID", "TARGET")], "dummy_submission.csv", row.names = FALSE)
```

```{r}
importance(bag.rf)
```



